steps:
- name: "alpine"
  id: "Replace values in the fast training config"
  entrypoint: "sh"
  args:
    - '-c'
    - |
      apk add --no-cache gettext
      envsubst < vertex_ai_config_fast.yaml > vertex_ai_config.yaml
  secretEnv: ['WANDB_API_KEY']

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Train on vertex AI with GPU (fast)'
  waitFor: ['Replace values in the fast training config']
  args: [
    'ai',
    'custom-jobs',
    'create',
    '--region',
    'europe-west1',
    '--display-name',
    '${_JOB_NAME}',
    '--config',
    'vertex_ai_config.yaml',
  ]
substitutions:
  _JOB_NAME: 'fast-training-${BUILD_ID}'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/WANDB_API_KEY/versions/latest
    env: 'WANDB_API_KEY'
