steps:
# ⚠️ CRITICAL: Build for linux/amd64 platform (required for GCP Vertex AI)
# The Dockerfile specifies FROM --platform=linux/amd64 which ensures correct platform
# Cloud Build runs on linux/amd64 machines, so images will be linux/amd64
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/container-registry/$_IMAGE_NAME',
    '-f',
    'dockerfiles/train.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/container-registry/$_IMAGE_NAME'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _IMAGE_NAME: 'train:latest'
